# Generated by Django 5.0.4 on 2024-04-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstParticipantScore', models.PositiveIntegerField(default=0)),
                ('secondParticipantScore', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('match', models.ManyToManyField(related_name='participantsMatch', to='tournamentManagement.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='firstParticipant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstParticipant', to='tournamentManagement.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='secondParticipant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondParticipant', to='tournamentManagement.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tournamentManagement.participant'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isStarted', models.BooleanField(default=False)),
                ('isDone', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(related_name='tournamentParticipants', to='tournamentManagement.participant')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentManagement.sport')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments',
            field=models.ManyToManyField(related_name='participantsTournaments', to='tournamentManagement.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentManagement.tournament'),
        ),
    ]
