# Generated by Django 5.0.4 on 2024-04-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentManagement', '0002_participant_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
