# Generated by Django 5.0.4 on 2024-04-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentManagement', '0003_alter_tournament_sport_delete_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='isDone',
        ),
    ]
